### ISSUE TITLE
Not opening file when we click on specific file

### ISSUE THREAD

**Issue by beinganonymous** [beinganonymous/File-Uploader-and-Downloder#3]
Here, i have one problem with my code is that when i click on specific file name then it does not shows that file content.
So i wanted file to show its content when i click on it
Here is image of list of files
![list](https://user-images.githubusercontent.com/30001594/56058534-43215b00-5d7f-11e9-982a-0df0a24ec517.png)

So this code displays filenames from mydatabase and create link for it.
And here is output
![output](https://user-images.githubusercontent.com/30001594/56058592-6d731880-5d7f-11e9-9bc5-3ac6fefc1bb3.png)
 that displays file content when we click on that file link.

**Comment by drigio** [comment]
Hi @beinganonymous ! What you are actually doing is not telling your *display_file.php* what file to display. What you can do over here is pass a **GET** parameter in *saveimage.php* like 

```php
<td><a href="display_file.php?path=".$row["images_path"]><?php echo $row["image_name"]; ?></a></td>
```

And in the *display_file.php* use the path sent through **GET** parameter to embed it in your web page.

Also check that the filename in your screenshot mentioned above is *save.php* and there is *saveimage.php* in your github repo

**Comment by beinganonymous** [comment]
So

**Comment by beinganonymous** [comment]
Solved
